table fact_orders
	lineageTag: a8f5a0fc-1c56-4949-8364-d40ac28fe822

	column order_id
		dataType: string
		lineageTag: 59a13de2-c9ee-440e-b9b9-57c64caae300
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: string
		lineageTag: b15a7262-a234-46d2-8822-238d82a3388e
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column order_status
		dataType: string
		lineageTag: ab326743-256f-436f-a939-3120624bd5b0
		summarizeBy: none
		sourceColumn: order_status

		annotation SummarizationSetBy = Automatic

	column order_purchase_timestamp
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6c487793-ba40-4171-b405-31a448325d4d
		summarizeBy: none
		sourceColumn: order_purchase_timestamp

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column order_approved_at
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5f5acf6e-9796-4b94-8415-2bf733fd4434
		summarizeBy: none
		sourceColumn: order_approved_at

		variation Variation
			isDefault
			relationship: 6854698c-e2c7-4e43-bba9-719198628140
			defaultHierarchy: LocalDateTable_202740a2-9260-4260-9814-17d24466a9c9.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column order_delivered_carrier_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3888b24b-984a-4b20-ae45-78c2135f9877
		summarizeBy: none
		sourceColumn: order_delivered_carrier_date

		variation Variation
			isDefault
			relationship: b6a160a4-0747-4954-a964-00016136099b
			defaultHierarchy: LocalDateTable_f4d23adc-e794-445f-bad1-4877b831c10c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column order_delivered_customer_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 17716825-e63d-4013-b8c4-e6b16c8f7e6d
		summarizeBy: none
		sourceColumn: order_delivered_customer_date

		variation Variation
			isDefault
			relationship: 82c7df79-070a-4b22-8f43-9c91799861e7
			defaultHierarchy: LocalDateTable_7ecb152e-a620-47f9-8cf4-2d4fac99160c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column order_estimated_delivery_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 00014231-0b1b-4805-b9b4-65012caf858c
		summarizeBy: none
		sourceColumn: order_estimated_delivery_date

		variation Variation
			isDefault
			relationship: 07a322c3-7f07-435a-bc9f-3170422f1dcb
			defaultHierarchy: LocalDateTable_f2d8ca2e-8714-4399-87a6-86bf7f64746e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition fact_orders = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("localhost", "olist_analytics"),
				    public_orders = Source{[Schema="public",Item="orders"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(public_orders,{{"order_purchase_timestamp", type date}, {"order_approved_at", type date}, {"order_delivered_carrier_date", type date}, {"order_delivered_customer_date", type date}, {"order_estimated_delivery_date", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

